# Generated by Django 5.0.7 on 2024-07-27 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_blog_delete_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 27, 22, 6, 20, 427858)),
        ),
    ]
