# Generated by Django 5.0.7 on 2024-07-28 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_blog_users_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 28, 22, 6, 20, 350948)),
        ),
    ]
