# Generated by Django 5.0.7 on 2024-07-29 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 29, 19, 23, 51, 84380)),
        ),
    ]
