# Generated by Django 5.0.7 on 2024-07-29 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_alter_blog_date_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='ask_members', to='posts.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 29, 20, 34, 37, 250969)),
        ),
        migrations.AlterField(
            model_name='member',
            name='blog',
            field=models.ManyToManyField(blank=True, related_name='members', to='posts.blog'),
        ),
    ]
