# Generated by Django 5.0.7 on 2024-07-29 21:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_remove_member_requests_alter_blog_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 29, 21, 22, 33, 730551)),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestors', to='posts.member'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptors', to='posts.member'),
        ),
    ]
