# Generated by Django 5.0.7 on 2024-07-30 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_alter_blog_date_alter_request_user_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 30, 5, 19, 13, 266333)),
        ),
    ]
