# Generated by Django 5.0.7 on 2024-07-30 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_request_status_alter_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 43, 2, 157526)),
        ),
    ]
