# Generated by Django 5.0.7 on 2024-07-30 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_remove_request_status_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 46, 17, 453852)),
        ),
    ]
