# Generated by Django 5.0.7 on 2024-07-30 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 30, 16, 52, 52, 658522)),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
