# Generated by Django 5.1 on 2024-09-10 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_alter_blog_date_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 10, 17, 25, 35, 37785)),
        ),
    ]
