# Generated by Django 5.0.7 on 2024-07-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_blog_date'),
        ('welcome_page', '0005_remove_userprofile_blogs_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recent_blogs',
            field=models.ManyToManyField(blank=True, related_name='users', to='posts.blog'),
        ),
    ]
