# Generated by Django 5.0.7 on 2024-07-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_blog_date'),
        ('welcome_page', '0007_remove_userprofile_recent_blogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recent_blogs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recent_blogs',
            field=models.ManyToManyField(blank=True, default=1, to='posts.blog'),
        ),
    ]
