# Generated by Django 5.0.7 on 2024-07-28 23:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0010_remove_recent_recent_blogs_recent_recent_blog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='user_for',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 23, 45, 40, 49723)),
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
