# Generated by Django 5.0.7 on 2024-07-28 23:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_blog_date'),
        ('welcome_page', '0012_alter_recent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 23, 46, 28, 148996)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_blog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.blog'),
        ),
    ]
