# Generated by Django 5.0.7 on 2024-07-28 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0014_alter_recent_date_alter_recent_user_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 23, 47, 0, 727751)),
        ),
    ]
