# Generated by Django 5.0.7 on 2024-07-28 23:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_blog_date'),
        ('welcome_page', '0016_alter_recent_date_alter_recent_user_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 23, 49, 6, 965475)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.blog'),
        ),
    ]
