# Generated by Django 5.0.7 on 2024-07-28 23:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_alter_blog_date'),
        ('welcome_page', '0018_alter_recent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 23, 54, 0, 61335)),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='posts.blog'),
        ),
    ]
