# Generated by Django 5.0.7 on 2024-07-29 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0019_alter_recent_date_alter_recent_recent_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 29, 17, 45, 29, 531900)),
        ),
    ]
