# Generated by Django 5.0.7 on 2024-07-29 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0022_alter_recent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 29, 20, 34, 37, 252548)),
        ),
    ]
