# Generated by Django 5.1 on 2024-09-30 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0033_alter_recent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 30, 17, 16, 57, 925572)),
        ),
    ]
