# Generated by Django 5.1 on 2024-10-09 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_page', '0036_alter_recent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 9)),
        ),
    ]
