# Generated by Django 5.0.7 on 2024-07-27 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_date'),
        ('posts', '0006_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ManyToManyField(to='posts.blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 22, 22, 45, 854744)),
        ),
    ]
