# Generated by Django 5.0.7 on 2024-07-27 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_blog_alter_post_date'),
        ('posts', '0007_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ManyToManyField(blank=True, to='posts.blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 22, 24, 55, 906973)),
        ),
    ]
